BingeWatchr/config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :capitulos
  resources :series
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, controllers: { registrations: 'users/registrations', omniauth_callbacks: "users/omniauth_callbacks" }# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "posts#index"
  devise_scope :user do get '/profile' => "main#profile" end
  devise_scope :user do get '/users/newson' => 'main#new0' end
  devise_scope :user do post '/users/createson' => 'users/registrations#create_son' end
  devise_scope :user do get '/users/edit_user/:id' => 'main#edit0' end
  devise_scope :user do post '/users/create_son' => 'users/registrations#create_son' end
  devise_scope :user do post '/users/delete_user' => 'users/registrations#delete_user' end
  devise_scope :user do post '/users/edit_user' => 'users/registrations#edit_user' end
  devise_scope :user do post '/users/create_admin' => 'users/registrations#create_admin' end

    devise_scope :user do
      get '/users/sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session2
    end

  get '/series' => 'series#index', as: :lista_series
  post '/series' => 'series#create', as: :create_new_series
  post '/comments' => 'comments#create'


  get 'posts' => 'posts#new', as: :new_post

  post '/rating_series' => 'rating_series#create', as: :create_rating

  post '/rating_capitulos' => 'rating_capitulos#create', as: :create_rating_capitulos
  get '/capitulos/:id' => 'rating_capitulos#show', as: :show_capitulo
  post '/seen_capitulos' => 'seen_capitulos#create', as: :seen
  delete '/seen_capitulos' => 'seen_capitulos#destroy', as: :unseen

  post '/favorites' => 'favorites#create', as: :fav
  delete 'favorites' => 'favorites#destroy', as: :unfav
  get '/favorites' => 'favorites#index', as: :show_fav

  post '/favorite_capitulos' => 'favorite_capitulos#create', as: :fav_capitulo
  delete 'favorite_capitulos' => 'favorite_capitulos#destroy', as: :unfav_capituo


  post '/watch_laters' => 'watch_later#create', as: :wl
  delete 'watch_laters' => 'watch_later#destroy', as: :unwl
  get '/watch_later' => 'watch_later#index', as: :show_wl


  get '/series/:id' => 'series#show', as: :tag

  get '/series/:id/capitulos' => 'capitulos#showsome', as: :show_some_capitulos

  put '/capitulos/:id', to: 'capitulos#update'

  get '/statistics', to: 'series#statistics'

  resources :posts
  # resources :users
end

BingeWatchr/app/controllers/series_controller.rb
class SeriesController < ApplicationController
  before_action :set_series, only: [:show, :edit, :update, :destroy]
  require 'net/http'
  require 'uri'
  # GET /series
  # GET /series.json
  def index
    if user_signed_in?
      if current_user.admin
        @series = Serie.all
      else
        @admins = User.where(admin: true)
        @series = Serie.where(user_id: current_user.id)
        @series = @series + Serie.where(user_id: current_user.parent_id)
        @admins.each do |adm|
          @series = @series.or(Serie.where(:user_id => adm.id))
        end
      end
    else
      @admins = User.where(:admin => true)
      @series = Serie.where(user_id: -1)
      @admins.each do |adm|
        @series = @series.or(Serie.where(:user_id => adm.id))
      end
    end
    unless @series.empty?
      @series = @series.where('lower(name) LIKE ?', "%#"+params[:search]+"%".downcase) if params[:search].present?
      @series = @series.where("tipo_id = ?", :tipo_id) if params[:tipo_id].present?
    end
  end

  # GET /series/1
  # GET /series/1.json
  def show
    @serie = Serie.find_by_id(params[:id])
    @capitulos = @serie.capitulos

    @comments = Comment.where(series_id: @serie.id)

    @user = current_user

  end

  # GET /statistics
  def statistics
    # Series mas rating
    @series_mostrated = Serie.joins("INNER JOIN rating_series ON series.id = rating_series.serie_id").distinct.select("name, series.id, sum(rating_series.value) as rating, count(rating_series.*) as times_rated").group("series.id").limit(5)
    # Series mas populares (favortios)
    @series_mostfavorited = Serie.joins("INNER JOIN favorites ON series.id = favorites.serie_id").distinct.select("series.id, name, count(favorites.*) as times").group("series.id").order("times DESC").limit(5)

    # Capitulos mas vistos
    @capitulos_mostwatched = Capitulo.joins(:serie, :seen_capitulos)
    .distinct
    .select("series.name as serie_name, capitulos.title as cap_name, capitulos.id, count(seen_capitulos.*) as times")
    .group("capitulos.id, series.name").order("times DESC").limit(5)

    @capitulos_mostrated = Capitulo.joins(:rating_capitulos, :serie)
    .distinct
    .select("capitulos.title as cap_name, series.name as serie_name, capitulos.id,
     sum(rating_capitulos.value) as rating, count(rating_capitulos.*) as times_rated")
     .group("capitulos.id, series.name").limit(5)


  end


  # GET /series/new
  def new
    @series = Serie.new
    @uid = current_user.id

  end

  def new0
    @uid = current_user.id
    @tipos = Tipo.all
  end

  # GET /series/1/edit
  def edit
  end

  # POST /series
  # POST /series.json
  def create
    uid = current_user.id
    users = User.where(parent_id: uid).all
    @series = Serie.new(series_params)
    if @series.save
      MailerMailer.mail1(users, @series.name).deliver
      flash[:notice] = "Successfully created Series!"
      redirect_to lista_series_url
    else
      flash[:alert] = "Error creating new Series!"
      render :new
    end
  end

  # PATCH/PUT /series/1
  # PATCH/PUT /series/1.json
  def update
    respond_to do |format|
      if @series.update(series_params)
        format.html { redirect_to @series, notice: 'Serie was successfully updated.' }
        format.json { render :show, status: :ok, location: @series }
      else
        format.html { render :edit }
        format.json { render json: @series.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /series/1
  # DELETE /series/1.json
  def destroy
    @series.destroy
    respond_to do |format|
      format.html { redirect_to lista_series_url, notice: 'Serie was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_series
      @series = Serie.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def series_params
      params.require(:serie).permit(:name, :year, :user_id, :tipo_id)
    end
end

BingeWatchr/app/helpers/series_helper.rb
module SeriesHelper
end

BingeWatchr/app/views/series/_form.html.erb
<%= simple_form_for(@series, :url => create_new_series_url, :id  => @series.id, :method => :post) do |f| %>
  <%= f.error_notification %>
  
  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :year %>
    <%= f.hidden_field :user_id, :value => @uid %>
    <%= f.collection_select :tipo_id, Tipo.all, :id, :name , { :prompt => 'Selecciona un tipo' } %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

BingeWatchr/app/views/series/edit.html.erb
<h1>Editing Series</h1>

<%= render 'form', series: @series %>

<%= link_to 'Show', @series %> |
<%= link_to 'Back', series_path %>

BingeWatchr/app/views/series/index.html.erb
<p id="notice"><%= notice %></p>  

  <%= form_tag lista_series_url, :method => 'get' do %>
    <p>
      <%= text_field_tag :search, params[:search] %>
      <%= select_tag 'tipo_id', options_for_select(Tipo.all.collect{ |u| [u.name, u.id] }), include_blank: true %>
      <%= submit_tag "Search", :name => nil %>
    </p>
  <% end %>

<head>
  <h1>Series</h1>
</head>
<% if user_signed_in? %>
<div class="text-center">
  <%= button_to 'New Series', new_series_path, :method => "get" %>
</div>
<% end %>

<body style="margin: 0px">

  <div class="series">
    <div class="container">
      <div class="cards row">
        <% @series.each do |series| %>
            <div class="card cola-xs-12" style="  margin: 0px">
              <% if series.image != nil %>
                <%= link_to image_tag(series.image, :style => "width: 100%"), series_path(series) %>
              <% else %>
                <%= link_to image_tag("/images/BW_placeholder.jpg", :style => "width: 100%"), series_path(series) %>
              <% end %>
              <h3><%= series.name %></h3>

            </div>
        <% end %>
      </div>
    </div>
  </div>
</body>

BingeWatchr/app/views/series/new.html.erb
<h1>New Series</h1>

<%= render 'form', series: @series %>

<%= link_to 'Back', '/series' %>

BingeWatchr/app/views/series/new0.html.erb
<%= form_tag("/series/newserie", method: "post") do %>
  <%= label_tag(:name, "Nombre de serie") %>
  <%= text_field_tag(:email) %>

  <%= label_tag(:year, "Año de la serie") %>
  <%= number_field_tag(:year), min: 0, max: 2017 %>

  <%= f.collection_select :tipo_id, Provider.order(:name),:id,:name, include_blank: true %>


  <%= hidden_field_tag(:user_id, @uid) %>


  <%= submit_tag("Crear serie") %>
<% end %>

BingeWatchr/app/views/series/show.html.erb
<p id="notice"><%= notice %></p>



<div style="display: flex;">
  <div>
    <% if @serie.image != nil %>
        <%= image_tag @serie.image, :style => "width: 250px" %>
    <% else %>
        <%= image_tag("/images/BW_placeholder.jpg", :style => "width: 200px") %>
    <% end %>
  </div>
  <div style="margin: 0 30px;">
    <h2><%= @serie.name %></h2>
    <h4>by <%= @serie.creator %></h4>
    <h4>Rated <%= @serie.maturity %></h4>
    <h4><%= @serie.year %></h4>

    <% if @user %>

        <% rating = RatingSerie.find_by(user: @user, serie: @serie) %>
        <% if rating %>
            <% full = rating.value.floor%>
            <% half = 0 %>
            <% if rating.value - full > 0 %>
                <% half = 1 %>
            <% end %>
            <% empty = 5 - full - half%>
            <% half %>

            <% (1..full).each do |i| %>
                <%= image_tag('star-on.png') %>
            <% end %>
            <% (1..half).each do |i| %>
                <%= image_tag('star-half.png') %>
            <% end %>
            <% (1..empty).each do |i| %>
                <%= image_tag('star-off.png') %>
            <% end %>
        <% else %>

            <%= form_tag '/rating_series', :method => 'post' do %>

                <%= number_field_tag :value, params[:value], in: 1..5, :style => "height: 35px; width: 35px; font-size: 100%", value:1 %>

                <%= hidden_field_tag(:serie, @serie.id) %>
                <%= hidden_field_tag(:user, @user.id) %>
                <%= submit_tag "Rate!", :name => nil %>

            <% end %>
        <% end %>

        <% fav = Favorite.find_by(user: @user, serie: @serie) %>
        <% if fav %>
            <%= form_tag '/favorites', :method => 'delete' do %>

                <%= hidden_field_tag(:serie, @serie.id) %>
                <%= hidden_field_tag(:user, @user.id) %>
                <%= submit_tag "Favorito!", :name => nil %>

            <% end %>
        <% else %>
            <%= form_tag '/favorites', :method => 'post' do %>

                <%= hidden_field_tag(:serie, @serie.id) %>
                <%= hidden_field_tag(:user, @user.id) %>
                <%= submit_tag "No es Favorito", :name => nil %>

            <% end %>
        <% end %>

    <% end %>
  </div>
  <div style="margin: 0 0 0 250px;">
    <% uri = URI.parse("https://accounts.spotify.com/api/token") %>
    <% request = Net::HTTP::Post.new(uri) %>
    <% request["Authorization"] = "Basic MzYyNmVhMDA5N2IyNDA3MTk1OWE5ZmQ2MmExOWIxNzA6ZDgzMGVmYjUzZWE0NDQ0ZWI2Y2JjODg1YmQwYzIxNWY=" %>
    <% request.set_form_data("grant_type" => "client_credentials",)%>
    <% req_options = {use_ssl: uri.scheme == "https",} %>
    <% response = Net::HTTP.start(uri.hostname, uri.port, req_options) do |http| %>
        <% http.request(request) %>
    <% end %>
    <% response = JSON.parse(response.body) %>

    <% uri = URI.parse("https://api.spotify.com/v1/search?q="+@serie.name.gsub(' ', '+')+"+soundtrack&type=playlist&limit=1") %>
    <% request = Net::HTTP::Get.new(uri) %>
    <% request["Accept"] = "application/json" %>
    <% request["Authorization"] = "Bearer " + response["access_token"] %>
    <% req_options = {use_ssl: uri.scheme == "https",} %>
    <% response = Net::HTTP.start(uri.hostname, uri.port, req_options) do |http| %>
        <% http.request(request) %>
    <% end %>
    <% response = JSON.parse(response.body) %>
    <h3>Soundtrack</h3>
    <%= content_tag(:iframe,'',width: 300, height: 300, frameborder: 0, allowtransparency: true, src: response["playlists"]["items"][0]["external_urls"]["spotify"].gsub('open.spotify.com/user', 'open.spotify.com/embed/user')) %>
    <br>
  </div>
</div>





<div class="text-center" style="display: flex;">
  <div style="margin: 0 0;">
    <%= button_to 'Ver Capítulos', show_some_capitulos_path(@serie), method: :get%>
  </div>
  <div style="margin: 0 30px;">
    <%= button_to 'Editar Serie', edit_series_path(@serie), method: :get %>
  </div>
  <div >
    <%= button_to 'Eliminar Serie', @serie, method: :delete, data: { confirm: 'Are you sure?' } %>
  </div>
</div>


<br>
<div>
  <table style="width: 800px; max-width: 75%">
    <tr><th>Commentarios</th></tr>

    <% @comments.each do |comment| %>

      <tr><td>
      <div style="display: flex;">
        <b><%= User.find_by_id(comment.user_id).email %>: </b>
        <div style="margin: 0 5px;">
        <%= comment.body %>
        </div>
        <% if user_signed_in? && current_user.id == comment.user_id %>
          <%= button_to 'Eliminar', comment, method: :delete, data: { confirm: 'Are you sure?' }, :style => "margin: 0 20px;" %>
        <% end %>
        </div>
      </td></tr>

    <% end %>


    <% if user_signed_in? %>

    <tr><td>
      <%= form_tag '/comments', :method => 'post' do %>

          <%= text_field_tag :body, params[:body], :style => "width: 80%; margin: 0 0" %>
          <%= hidden_field_tag(:user_id, current_user.id) %>
          <%= hidden_field_tag(:series_id, @serie.id) %>
          <%= submit_tag "Commentar", :name => nil, :style => "margin: 0 0" %>

      <% end %>
    </td></tr>

    <% end %>
  </table>
</div>



</div>

BingeWatchr/app/views/series/statistics.html.erb
<h3> Top 5 series mejor rankeadas </h3>
<% @series_mostrated.each do |s| %>
  <p>
    <%= s.name %><br>
    Rating promedio: <%= s.rating / s.times_rated %>
  </p>
<%end%>

<h3> Top 5 capitulos mejor rankeados </h3>
<% @capitulos_mostrated.each do |s| %>
  <p>
    Serie: <%= s.serie_name %><br>
    Capitulo: <%= s.cap_name %><br>
    <%= s.rating/s.times_rated %> veces vista.
  </p>
<%end%>

<h3> Top 5 series con mas favoritos </h3>
  <% @series_mostfavorited.each do |s| %>
    <p>
      <%= s.name %><br>
      Vista <%= s.times %> veces.
    </p>
<%end%>


<h3> Top 5 capitulos mas vistos </h3>
  <% @capitulos_mostwatched.each do |s| %>
    <p>
      Serie: <%= s.serie_name %><br>
      Capitulo: <%= s.cap_name %><br>
      Visto <%= s.times %> veces.
    </p>
<%end%>