BingeWatchr/config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :capitulos
  resources :series
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, controllers: { registrations: 'users/registrations', omniauth_callbacks: "users/omniauth_callbacks" }# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "posts#index"
  devise_scope :user do get '/profile' => "main#profile" end
  devise_scope :user do get '/users/newson' => 'main#new0' end
  devise_scope :user do post '/users/createson' => 'users/registrations#create_son' end
  devise_scope :user do get '/users/edit_user/:id' => 'main#edit0' end
  devise_scope :user do post '/users/create_son' => 'users/registrations#create_son' end
  devise_scope :user do post '/users/delete_user' => 'users/registrations#delete_user' end
  devise_scope :user do post '/users/edit_user' => 'users/registrations#edit_user' end
  devise_scope :user do post '/users/create_admin' => 'users/registrations#create_admin' end

    devise_scope :user do
      get '/users/sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session2
    end

  get '/series' => 'series#index', as: :lista_series
  post '/series' => 'series#create', as: :create_new_series
  post '/comments' => 'comments#create'


  get 'posts' => 'posts#new', as: :new_post

  post '/rating_series' => 'rating_series#create', as: :create_rating

  post '/rating_capitulos' => 'rating_capitulos#create', as: :create_rating_capitulos
  get '/capitulos/:id' => 'rating_capitulos#show', as: :show_capitulo
  post '/seen_capitulos' => 'seen_capitulos#create', as: :seen
  delete '/seen_capitulos' => 'seen_capitulos#destroy', as: :unseen

  post '/favorites' => 'favorites#create', as: :fav
  delete 'favorites' => 'favorites#destroy', as: :unfav
  get '/favorites' => 'favorites#index', as: :show_fav

  post '/favorite_capitulos' => 'favorite_capitulos#create', as: :fav_capitulo
  delete 'favorite_capitulos' => 'favorite_capitulos#destroy', as: :unfav_capituo


  post '/watch_laters' => 'watch_later#create', as: :wl
  delete 'watch_laters' => 'watch_later#destroy', as: :unwl
  get '/watch_later' => 'watch_later#index', as: :show_wl


  get '/series/:id' => 'series#show', as: :tag

  get '/series/:id/capitulos' => 'capitulos#showsome', as: :show_some_capitulos

  put '/capitulos/:id', to: 'capitulos#update'

  get '/statistics', to: 'series#statistics'

  resources :posts
  # resources :users
end

BingeWatchr/app/models/post.rb
class Post < ApplicationRecord
end

BingeWatchr/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, only: [:edit, :update, :show, :delete]

  # Index action to render all posts
  def index
    @posts = Post.all.sort_by(&:created_at).reverse
    
  end

  # New action for creating post
  def new
    @post = Post.new

  end

  # Create action saves the post into database
  def create
    @post = Post.new(post_params)
    if @post.save
      flash[:notice] = "Successfully created post!"
      redirect_to post_path(@post)
    else
      flash[:alert] = "Error creating new post!"
      render :new
    end
  end

  # Edit action retrives the post and renders the edit page
  def edit
  end

  # Update action updates the post with the new information
  def update
    if @post.update_attributes(post_params)
      flash[:notice] = "Successfully updated post!"
      redirect_to post_path(@post)
    else
      flash[:alert] = "Error updating post!"
      render :edit
    end
  end

  # The show action renders the individual post after retrieving the the id
  def show
  end

  # The destroy action removes the post permanently from the database
  def destroy
    if @post.destroy
      flash[:notice] = "Successfully deleted post!"
      redirect_to posts_path
    else
      flash[:alert] = "Error updating post!"
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :body)
  end

  def find_post
    @post = Post.find(params[:id])
  end
end

BingeWatchr/app/helpers/posts_helper.rb
module PostsHelper
end

BingeWatchr/app/views/posts/_form.html.erb
<%= simple_form_for @post do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= "#{pluralize(@post.errors.count, "error")} prohibited this post from being saved:" %>
      </h2>
      <ul>
        <% @post.errors.full_messages.each do |msg| %>
          <li>
            <%= msg %>
          </li>
          <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.input :title, class: "form-control" %>
  </div>
  <br/>
  <div class="form-group">
    <%= f.input :body, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.button :submit %>
  </div>
<% end %>

BingeWatchr/app/views/posts/edit.html.erb
<div class="container">
  
<h2>Edit Post</h2>

<%= render "posts/form" %>
<%= button_to "Home", root_path, :method => "get" %>
</div>
</body>

BingeWatchr/app/views/posts/index.html.erb
<link rel="stylesheet" type="text/css" href="mystyle.css">
<body style="margin: 0px">
<div class="container" >

  <% if user_signed_in? %>
      <% if current_user.admin %>
          <div class="text-center">
            <%= button_to 'New Post', new_post_path, :method => "get" %>
          </div>
          <% end %>

  <% end %>
  

  <div class="row">
    <% @posts.each do |post| %>
    <div class="col-xs-12">
      <div class="text-center">
        <h2><%= post.title %></h2>
        <h6><%= post.created_at.strftime('%b %d, %Y') %></h6>
      </div>

      <div>
        <%= raw(post.body).truncate(358) %>
      </div>

      <div class="text-center">
        <%= button_to "READ MORE", post_path(post), :method => "get" %>
      </div>
      <br>
    </div>
    <% end %>
    
  </div>
  
    
  

</div>
</body>

BingeWatchr/app/views/posts/new.html.erb
<body style="margin: 0px">
<div class="container">
  
<h2>Create New Post</h2>

<%= render "posts/form" %>
<%= button_to "Home", root_path, :method => "get" %>
</div>
</body>

BingeWatchr/app/views/posts/show.html.erb
<body style="margin: 0px">


<div class="container">

<div class="col-sm-11 col-xs-12 blog-content">
  <h2 class="text-center"><%= @post.title %></h2>
  <h5 class="text-center"><%= @post.created_at.strftime('%b %d, %Y') %></h5>
  <div><%= raw @post.body %></div>
  <%= button_to "Home", root_path, :method => "get" %>
</div>
</div>
<!-- social -->
<div class="fb-share-button" data-href="<%= request.original_url %>" data-layout="button" data-size="large" data-mobile-iframe="true"><a class="fb-xfbml-parse-ignore" target="_blank" href="https://www.facebook.com/sharer/sharer.php?u="+<%=request.original_url%> >Compartir</a></div>
<!-- # <%= social_share_button_tag(@post.title) %> -->
<!-- end social -->
</body>