BingeWatchr/config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :capitulos
  resources :series
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, controllers: { registrations: 'users/registrations', omniauth_callbacks: "users/omniauth_callbacks" }# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "posts#index"
  devise_scope :user do get '/profile' => "main#profile" end
  devise_scope :user do get '/users/newson' => 'main#new0' end
  devise_scope :user do post '/users/createson' => 'users/registrations#create_son' end
  devise_scope :user do get '/users/edit_user/:id' => 'main#edit0' end
  devise_scope :user do post '/users/create_son' => 'users/registrations#create_son' end
  devise_scope :user do post '/users/delete_user' => 'users/registrations#delete_user' end
  devise_scope :user do post '/users/edit_user' => 'users/registrations#edit_user' end
  devise_scope :user do post '/users/create_admin' => 'users/registrations#create_admin' end

    devise_scope :user do
      get '/users/sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session2
    end

  get '/series' => 'series#index', as: :lista_series
  post '/series' => 'series#create', as: :create_new_series
  post '/comments' => 'comments#create'


  get 'posts' => 'posts#new', as: :new_post

  post '/rating_series' => 'rating_series#create', as: :create_rating

  post '/rating_capitulos' => 'rating_capitulos#create', as: :create_rating_capitulos
  get '/capitulos/:id' => 'rating_capitulos#show', as: :show_capitulo
  post '/seen_capitulos' => 'seen_capitulos#create', as: :seen
  delete '/seen_capitulos' => 'seen_capitulos#destroy', as: :unseen

  post '/favorites' => 'favorites#create', as: :fav
  delete 'favorites' => 'favorites#destroy', as: :unfav
  get '/favorites' => 'favorites#index', as: :show_fav

  post '/favorite_capitulos' => 'favorite_capitulos#create', as: :fav_capitulo
  delete 'favorite_capitulos' => 'favorite_capitulos#destroy', as: :unfav_capituo


  post '/watch_laters' => 'watch_later#create', as: :wl
  delete 'watch_laters' => 'watch_later#destroy', as: :unwl
  get '/watch_later' => 'watch_later#index', as: :show_wl


  get '/series/:id' => 'series#show', as: :tag

  get '/series/:id/capitulos' => 'capitulos#showsome', as: :show_some_capitulos

  put '/capitulos/:id', to: 'capitulos#update'

  get '/statistics', to: 'series#statistics'

  resources :posts
  # resources :users
end

BingeWatchr/app/models/comment.rb
class Comment < ApplicationRecord
end

BingeWatchr/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to series_path(Serie.find_by_id(@comment.series_id)), notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    series_id = @comment.series_id
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to series_path(Serie.find_by_id(series_id)), notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.permit(:user_id, :body, :series_id)
    end
end

BingeWatchr/app/helpers/comments_helper.rb
module CommentsHelper
end

BingeWatchr/app/views/comments/_form.html.erb
<%= simple_form_for(@comment) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :user_id %>
    <%= f.input :body %>
    <%= f.input :series_id %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

BingeWatchr/app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

BingeWatchr/app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Body</th>
      <th>Series</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.user_id %></td>
        <td><%= comment.body %></td>
        <td><%= comment.series_id %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

BingeWatchr/app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', comments_path %>

BingeWatchr/app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @comment.user_id %>
</p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<p>
  <strong>Series:</strong>
  <%= @comment.series_id %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>