BingeWatchr/config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :capitulos
  resources :series
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, controllers: { registrations: 'users/registrations', omniauth_callbacks: "users/omniauth_callbacks" }# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "posts#index"
  devise_scope :user do get '/profile' => "main#profile" end
  devise_scope :user do get '/users/newson' => 'main#new0' end
  devise_scope :user do post '/users/createson' => 'users/registrations#create_son' end
  devise_scope :user do get '/users/edit_user/:id' => 'main#edit0' end
  devise_scope :user do post '/users/create_son' => 'users/registrations#create_son' end
  devise_scope :user do post '/users/delete_user' => 'users/registrations#delete_user' end
  devise_scope :user do post '/users/edit_user' => 'users/registrations#edit_user' end
  devise_scope :user do post '/users/create_admin' => 'users/registrations#create_admin' end

    devise_scope :user do
      get '/users/sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session2
    end

  get '/series' => 'series#index', as: :lista_series
  post '/series' => 'series#create', as: :create_new_series
  post '/comments' => 'comments#create'


  get 'posts' => 'posts#new', as: :new_post

  post '/rating_series' => 'rating_series#create', as: :create_rating

  post '/rating_capitulos' => 'rating_capitulos#create', as: :create_rating_capitulos
  get '/capitulos/:id' => 'rating_capitulos#show', as: :show_capitulo
  post '/seen_capitulos' => 'seen_capitulos#create', as: :seen
  delete '/seen_capitulos' => 'seen_capitulos#destroy', as: :unseen

  post '/favorites' => 'favorites#create', as: :fav
  delete 'favorites' => 'favorites#destroy', as: :unfav
  get '/favorites' => 'favorites#index', as: :show_fav

  post '/favorite_capitulos' => 'favorite_capitulos#create', as: :fav_capitulo
  delete 'favorite_capitulos' => 'favorite_capitulos#destroy', as: :unfav_capituo


  post '/watch_laters' => 'watch_later#create', as: :wl
  delete 'watch_laters' => 'watch_later#destroy', as: :unwl
  get '/watch_later' => 'watch_later#index', as: :show_wl


  get '/series/:id' => 'series#show', as: :tag

  get '/series/:id/capitulos' => 'capitulos#showsome', as: :show_some_capitulos

  put '/capitulos/:id', to: 'capitulos#update'

  get '/statistics', to: 'series#statistics'

  resources :posts
  # resources :users
end

BingeWatchr/app/models/capitulo.rb
class Capitulo < ApplicationRecord
  belongs_to :serie
  has_many :seen_capitulos
  has_many :rating_capitulos
  has_many :watch_laters
  has_many :favorite_capitulos
end

BingeWatchr/app/controllers/capitulos_controller.rb
class CapitulosController < ApplicationController
  before_action :set_capitulo, only: [:show, :edit, :update, :destroy]

  # GET /capitulos
  # GET /capitulos.json
  def index
    @capitulos = Capitulo.all
  end

  # GET /capitulos/1
  # GET /capitulos/1.json
  def show
    @user = current_user
  end

  def showsome
    @serie = Serie.find_by_id(params[:id])
    @capitulos = @serie.capitulos
    @user = current_user.id
  end

  # GET /capitulos/new
  def new
    @capitulo = Capitulo.new
  end

  # GET /capitulos/1/edit
  def edit
    @capitulo = Capitulo.find_by_id(params[:id])
  end

  # POST /capitulos
  # POST /capitulos.json
  def create
    @capitulo = Capitulo.new(capitulo_params)

    respond_to do |format|
      if @capitulo.save
        uid = current_user.id
        users = User.where(parent_id: uid).all
        MailerMailer.mail1(users, @capitulo.title).deliver
        format.html { redirect_to @capitulo, notice: 'Capitulo was successfully created.' }
        format.json { render :show, status: :created, location: @capitulo }
      else
        format.html { render :new }
        format.json { render json: @capitulo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /capitulos/1
  # PATCH/PUT /capitulos/1.json
  def update
    @capitulo = Capitulo.find_by_id(params[:id])

      if @capitulo.update(capitulo_params)
        redirect_to capitulos_path, :notice => 'Capitulo was successfully updated.'
      else
        render "edit"
    end

  end

  # DELETE /capitulos/1
  # DELETE /capitulos/1.json
  def destroy
    @capitulo.destroy
    respond_to do |format|
      format.html { redirect_to capitulos_url, notice: 'Capitulo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_capitulo
      @capitulo = Capitulo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def capitulo_params
      params.require(:capitulo).permit(:name, :serie_id, :parent_id, :id)
    end
end

BingeWatchr/app/helpers/capitulos_helper.rb
module CapitulosHelper
end

BingeWatchr/app/views/capitulos/_form.html.erb
<%= simple_form_for(@capitulo) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :episode %>
    <%= f.input :season %>
    <%= f.association :serie %>
    <%= f.input :description%>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

BingeWatchr/app/views/capitulos/edit.html.erb
<h1>Editing Capitulo</h1>

    <%= simple_form_for(@capitulo) do |f| %>


          <%= f.input :title %>
          <%= f.input :episode %>
          <%= f.input :season %>
          <%= f.association :serie %>
          <%= f.input :rating, collection: 1..5, as: :radio_buttons %>
          <%= f.input :seen, as: :check_boxes %>
          <%= f.input :description%>


          <%= f.button :submit %>

    <% end %>

<%= link_to 'Show', @capitulo %> |
<%= link_to 'Back', capitulos_path %>

BingeWatchr/app/views/capitulos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Capitulos</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Serie</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @capitulos.each do |capitulo| %>
      <tr>
        <td><%= capitulo.title %></td>
        <td><%= capitulo.serie.name %></td>
        <td><%= link_to 'Show', capitulo %></td>
        <td><%= link_to 'Edit', edit_capitulo_path(capitulo) %></td>
        <td><%= link_to 'Destroy', capitulo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Capitulo', new_capitulo_path %>

BingeWatchr/app/views/capitulos/new.html.erb
<h1>New Capitulo</h1>

<%= render 'form', capitulo: @capitulo %>

<%= link_to 'Back', capitulos_path %>

BingeWatchr/app/views/capitulos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @capitulo.title %>
</p>

<p> <%= @capitulo.serie.name%> : <%= @capitulo.season%>x<%= @capitulo.episode%>
</p>
<p>
  <strong>Descripcion:</strong>
  <%= @capitulo.description%>
</p>

<br>

  <% if @user %>

      <% rating = RatingCapitulo.find_by(user: @user, capitulo: @capitulo) %>
      <% if rating %>
          <% full = rating.value.floor%>
          <% half = 0 %>
          <% if rating.value - full > 0 %>
              <% half = 1 %>
          <% end %>
          <% empty = 5 - full - half%>
          <% half %>

          <% (1..full).each do |i| %>
              <%= image_tag('star-on.png') %>
          <% end %>
          <% (1..half).each do |i| %>
              <%= image_tag('star-half.png') %>
          <% end %>
          <% (1..empty).each do |i| %>
              <%= image_tag('star-off.png') %>
          <% end %>
      <% else %>

          <%= form_tag '/rating_capitulos', :method => 'post' do %>

              <%= number_field_tag :value, params[:value], in: 1..5, value: 1 %>
              <%= hidden_field_tag(:capitulo, @capitulo.id) %>
              <%= hidden_field_tag(:user, @user.id) %>
              <%= submit_tag "Rate!", :name => nil %>

          <% end %>

      <% end %>

    </br>
    </br>
    </br>

    <% seen = SeenCapitulo.find_by(user: @user, capitulo: @capitulo) %>
    <% if seen %>

        <div >
          <%= form_tag '/seen_capitulos', :method => 'delete' do %>

              <%= hidden_field_tag(:capitulo, @capitulo.id) %>
              <%= hidden_field_tag(:user, @user.id) %>
              <%= submit_tag "Visto", :name => nil %>

          <% end %>
        </div>

    <%else%>
        <%= form_tag '/seen_capitulos', :method => 'post' do %>

            <%= hidden_field_tag(:capitulo, @capitulo.id) %>
            <%= hidden_field_tag(:user, @user.id) %>
            <%= submit_tag "No Visto", :name => nil %>

        <% end %>
    <% end %>
    <% fav = FavoriteCapitulo.find_by(user: @user, capitulo: @capitulo) %>
    <% if fav %>

        <div >
          <%= form_tag '/favorite_capitulos', :method => 'delete' do %>

              <%= hidden_field_tag(:capitulo, @capitulo.id) %>
              <%= hidden_field_tag(:user, @user.id) %>
              <%= submit_tag "Favorito!", :name => nil %>

          <% end %>
        </div>

    <%else%>

        <%= form_tag '/favorite_capitulos', :method => 'post' do %>

            <%= hidden_field_tag(:capitulo, @capitulo.id) %>
            <%= hidden_field_tag(:user, @user.id) %>
            <%= submit_tag "No es Favorito", :name => nil %>

        <% end %>
    <% end %>

    </br>
    </br>
    </br>

    <% wl = WatchLater.find_by(user: @user, capitulo: @capitulo) %>
    <% if wl %>

        <strong>Está en Watch Later</strong>

        <div >
          <%= form_tag '/watch_laters', :method => 'delete' do %>

              <%= hidden_field_tag(:capitulo, @capitulo.id) %>
              <%= hidden_field_tag(:user, @user.id) %>
              <%= submit_tag "Eliminar", :name => nil %>

          <% end %>
        </div>

    <%else%>
        <strong>No está en Watch Later</strong>


        <%= form_tag '/watch_laters', :method => 'post' do %>

            <%= hidden_field_tag(:capitulo, @capitulo.id) %>
            <%= hidden_field_tag(:user, @user.id) %>
            <%= submit_tag "Agregar", :name => nil %>

        <% end %>
    <% end %>
  <% end %>

</br>
</br>

<div style="margin: 0 0;">
  <%= button_to 'Edit', edit_capitulo_path(@capitulo)%>
</div>

<div style="margin: 0 30px;">
  <%= button_to 'Back', capitulos_path %>
</div>

BingeWatchr/app/views/capitulos/showsome.html.erb
<p id="notice" xmlns="http://www.w3.org/1999/html"><%= notice %></p>

<head>
  <h1>Capitulos de <%=@serie.name %></h1>
</head>

<body style="margin: 0px">

</div>
<div style="margin: 0 30px;">
  <%= button_to 'New Episode', new_capitulo_path, method: :get %>
</div>

<div class="capitulos">
  <div class="container">
    <div class="cards row">
      <% @capitulos.each do |episode| %>
          <div class="card col-xs-12">
            <h1><%= episode.title %></h1>
            <p>Episodio <%= episode.episode%>, Temporada <%= episode.season%></p></br>

            <div style="margin: 0 30px;">
              <%= button_to 'Learn More', capitulo_path(episode), method: :get %>
            </div>

          </div>
      <% end %>
    </div>
  </div>
</div>
</body>